version: '3.8'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload

  react:
    build: ./react/finance-app
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
